stages:
  - release
  - format
  - test

release:
  stage: release
  image: python:latest
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing --verbose dist/* -u __token__ -p ${TEST_PYPI_API_TOKEN}
  only:
    - tags

format:
  stage: format
  image: python:latest
  script:
    - pip install black
    - pip install "black[jupyter]"
    - black --check .

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/
