stages:
  - release
  - format
  - test
  - install

release:
  stage: release
  image: python:latest
  script:
    - pip install twine setuptools
    - python setup.py sdist bdist_wheel
    - twine upload --repository pypi --skip-existing --verbose dist/* -u __token__ -p ${PYPI_API_TOKEN}
  only:
    - tags

format:
  stage: format
  image: python:latest
  script:
    - pip install black
    - pip install "black[jupyter]"
    - black --check .

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/

install:
  stage: install
  image: python:latest
  script:
    - pip install s2stools
    - python -c "import s2stools"
