stages:
  - release

release:
  stage: release
  image: python:latest
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing --verbose dist/* -u __token__ -p ${TEST_PYPI_API_TOKEN}
  only:
    - tags

formatting:
  image: python:latest
  script:
    - pip install black
    - black --check .

testing:
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest tests/
